export { useServicoService } from './Servico.Service'
export { useLavaRapidoService } from './LavaRapido.Service'
export { useUsuarioService } from './Usuario.Service'
export { useAgendamentoService } from './Agendamento.Service'
export { useDashboardService } from './Dashboard.Service'